#cloud-config

package_update: true

packages:
  - apache2
  - git

runcmd:
  - rm -f /var/www/html/index.html
  - git clone https://github.com/Mishomoon/cloud-services-week7.git /tmp/week7
  - cp /tmp/week7/index.html /var/www/html/index.html
  - cp -r /tmp/week7/screenshots /var/www/html/
  - cp "/tmp/week7/Cloud service (6).pdf" "/var/www/html/Cloud service (6).pdf"
  - systemctl enable apache2
  - systemctl restart apache2